#.coveralls.yml

service_name: travis-ci

src_dir: bookshelf/src
# It doesn't contain helloworld/silex, but there is no issues with the
# report.
# TODO: Confirm what is src_dir is for.

coverage_clover:
  - bookshelf/build/logs/clover.xml
  - helloworld/silex/build/logs/clover.xml

json_path: build/logs/coveralls-upload.json
exclude_no_stmt: true
